language: android
sudo: required 
jdk: oraclejdk8

android:
  components:
    - build-tools=27.0.3

addons:
  sonarcloud:
    organization: "daskie-github"
    token:
      secure: "e3d5b00b78e2af8d0a0c63ff6edf089e6d21bf6f"

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - cp ./licenses/* "$ANDROID_HOME/licenses/"

before_script:
  - chmod +x gradlew

script:
  - ./gradlew clean build connectedCheck --stacktrace
  - sonar-scanner


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'