language: android
sudo: required
jdk: oraclejdk8

android:
  components:
  - tools
  - build-tools=27.0.3
  - android-27
  - platform-tools
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository

  - sys-img-armeabi-v7a-android-27

# install: true

addons:
  sonarcloud:
    organization: "daskie-github"
    token:
      secure: "e3d5b00b78e2af8d0a0c63ff6edf089e6d21bf6f"


before_script:
  - pwd
  - ls -al
  - chmod +x gradlew

script:
  - ./gradlew assembleDebug --stacktrace
  - sonar-scanner


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'