language: android

android:
  components:
  - build-tools=27.0.3
  - android-27
  - add-on
  - extra
  # - extra-google-google_play_services
  # - extra-google-m2repository
  # - extra-android-m2repository
  # - addon-google_apis-google-27

  - sys-img-armeabi-v7a-android-27

sudo: false
install: true

addons:
  sonarcloud:
    organization: "daskie-github"
    token:
      secure: "e3d5b00b78e2af8d0a0c63ff6edf089e6d21bf6f"
jdk:
  - oraclejdk8
script:
  - ./gradlew sonarqube
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'