language: android
sudo: required
jdk: oraclejdk8

android:
  components:
  - tools
  - tools
  - build-tools=27.0.3
  - android-27
  - platform-tools
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository

  # - sys-img-armeabi-v7a-android-27

# install: true

 licenses:
  - android-sdk-license-.+
  - google-gdk-license-.+


addons:
  sonarcloud:
    organization: "daskie-github"
    token:
      secure: "e3d5b00b78e2af8d0a0c63ff6edf089e6d21bf6f"


before_script:
  - chmod +x gradlew

script:
  - ./gradlew connectedCheck
  - ./gradlew clean --stacktrace
  - ./gradlew build --stacktrace
  - sonar-scanner


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'