package cscCCCIX.geocracy.states;

public enum GameAction {
    TOGGLE_SETTINGS_VISIBILITY,
    TOGGLE_GAME_INFO_VISIBILITY,
    CLOSE_OVERLAY_ACTION,
    TERRITORY_SELECTED,
    ATTACK_TAPPED,
    ADD_UNIT_TAPPED,
    REMOVE_UNIT_TAPPED,
    CONFIRM_UNITS_TAPPED,
    CANCEL_ACTION
}
