package csc309.geocracy.states;

public enum GameAction {
    TOGGLE_SETTINGS_VISIBILITY,
    TOGGLE_GAME_INFO_VISIBILITY,
    CLOSE_OVERLAY_ACTION,
    TERRITORY_SELECTED,
    ATTACK_TAPPED,
    CONFIRM_UNITS_TAPPED,
    CANCEL_ACTION
}
