package csc309.geocracy.game;

public enum UIEvent {
    SHOW_ATTACK_MODE_BUTTON,
    HIDE_ATTACK_MODE_BUTTON,
    SET_ATTACK_MODE_ACTIVE,
    SET_ATTACK_MODE_INACTIVE,
    SHOW_CANCEL_BUTTON,
    HIDE_CANCEL_BUTTON
}
