package csc309.geocracy.game;

public enum UIEvent {
    SHOW_ATTACK_MODE_BUTTON,
    HIDE_ATTACK_MODE_BUTTON,
    SHOW_UPDATE_UNITS_MODE_BUTTONS,
    HIDE_UPDATE_UNITS_MODE_BUTTONS,
    SET_ATTACK_MODE_ACTIVE,
    SET_ATTACK_MODE_INACTIVE,
    SHOW_CANCEL_BUTTON,
    HIDE_CANCEL_BUTTON,
    SHOW_CLOSE_OVERLAY_BUTTON,
    HIDE_CLOSE_OVERLAY_BUTTON
}
