package csc_cccix.geocracy.old_states;

public enum GameAction {
    SETTINGS_TAPPED,
    GAME_INFO_TAPPED,
    CLOSE_OVERLAY_TAPPED,
    TERRITORY_SELECTED,
    ATTACK_TAPPED,
    FORTIFY_TAPPED,
    ADD_UNIT_TAPPED,
    REMOVE_UNIT_TAPPED,
    CONFIRM_UNITS_TAPPED,
    CONFIRM_TAPPED,
    CANCEL_TAPPED,
    END_TURN_TAPPED,
    SAVE_GAME_TAPPED
}
